Training/urls.py
from django.contrib import admin
from django.urls import path
from . import views

#to access links all over the html files
app_name="training"
urlpatterns = [
    #this end point has a form to allow user to submit for predicted insurance quote
    path('main/', views.Home_Page,name="main_page"),
    #navigates to about page which has details about the website
    path('about/', views.Test,name="test"),

    #navigates to analysis page where the demographics is shown clearly between
    #different variables
    path('analysis/', views.stack_chart,name="analysis"),

]

Training/models.py
from django.db import models

# Create your models here.

Training/views.py
from django.shortcuts import render,redirect
from django.core import serializers
import json
import csv
from django.contrib.staticfiles.storage import staticfiles_storage
from django.shortcuts import render
import time
from collections import defaultdict, Counter
import collections
from os import path
import joblib
import concurrent.futures
import pandas as pd
import numpy as np

# importing saved prediction model
clf_G = joblib.load(path.join(path.dirname(__file__) , "clf_G.sav"))
def predict_G(state, G1, G2):
    # creating 11 input variables
    features = [0] * 11
    # last G
    features[G1 - 1] = 1
    # second last G
    features[G2 + 3] = 1
    # checking the state
    if state == 'FL':
        features[8] = 1
    elif state == 'ND':
        features[9] = 1
    elif state == 'SD':
        features[10] = 1
    # returning the predicted value of G
    return clf_G.predict([features])
#contains dataframe
class TrainingData:
    def __init__(self):
        self.train_data_path = path.join(path.dirname(__file__) , "train.csv") # retreiving training data path
        # columns for aggregation
        self.columns = ['shopping_pt', 'state', 'group_size', 'homeowner', 'car_age', 'car_value', 'age_oldest',
                'age_youngest', 'married_couple', 'C_previous', 'duration_previous', 'A', 'B', 'C', 'D', 'E', 'F', 'G']
        #importing data
        self.df = pd.read_csv(self.train_data_path)
        # last row of data
        self.last_row = self.df.tail(1)
        # size of dataset
        self.count = len(self.df)
        print(self.count)
        # extracting actual purchase
        self.df = self.df[self.df['record_type'] == 1]
        # dictionary to store aggregation of data
        self.data = dict()
        # start aggregation of data
        self.extract_data()
    def extract_data(self):
        # taking each column at a time
        for col in self.columns:
            # column reference to new dictionary
            self.data[col] = dict()
            # dependent variables
            for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']:
                # If column and dependent variables are same, No need to aggregate
                if col == i:
                    continue
                # aggregation of data by column and dependent variable
                try:
                    details = self.df.groupby([col, i]).size().reset_index().to_numpy().astype(int).tolist()
                except:
                    details = self.df.groupby([col, i]).size().reset_index().to_numpy().tolist()
                # dependent variable reference to new dictionary which has default value as dictionary
                self.data[col][i] = defaultdict(dict)
                # a: value of column
                # b: value of dependent variable
                # count: number of rows with value of column as a and value of dependent variable as b
                for a, b, count in details:
                    self.data[col][i][a][b] = count
    # To update the csv dataframe
    def update_data(self, new_df):
        # update the length of dataset
        self.count += len(new_df)
        # extract the purchase columns
        new_df  = new_df[new_df['record_type'] == 1]
        # set new last row
        self.last_row = new_df.tail(1)
        # appending the new purchases to dataframe
        self.df = self.df.append(new_df, ignore_index = True)
        #print(new_df,self.df.tail(), self.count)
        # updating the dictionary
        for col in self.columns:
            for i in ['A', 'B', 'C', 'D', 'E', 'F', 'G']:
                if col == i:
                    continue
                # aggregating the newly added data
                try:
                    details = new_df.groupby([col, i]).size().reset_index().to_numpy().astype(int).tolist()
                except:
                    details = new_df.groupby([col, i]).size().reset_index().to_numpy().tolist()
                for a, b, count in details:
                    self.data[col][i][a][b] += count
    def check_for_update(self):
        # read the last rows while skipping rows from 1..total rows - 1
        try:
            new_df = pd.read_csv(self.train_data_path, skiprows=range(1,self.count))
            # Check if dataset is updated
            if not int(new_df.tail(1)['customer_ID']) == int(self.last_row['customer_ID']):
                # update the dictionary and dataframe with new entries
                self.update_data(new_df.iloc[1:])
        except:
            print("CSV file is lost some data")

def stack_chart(request):
    ''' format of data : first_index = columns(refer TrainingData class above to know about all columns available)
    # second_index:  dependent variables columns [A,B,C,D,E,F,G]
    # third_index: value of first_column eg: shopping_pt has [3, 13] values
    # fourth_index: value of second_column i.e values of A, B.....G
    # How to process this data?: first select first and second column value from drop down
    # and then use it directly inside javascript object to extract the values. then use two for loops to
    # access count values for every value of column and dependent variables.
    '''
    train.check_for_update() #to detect any updation to training data
    # converting it into JSON object.
    context = json.dumps(train.data)
    # sending data to frontend.
    return render(request, 'Training/analysis.html', {'context':context})

# Create your views here.
def Home_Page(request):
    #dictionary to store and send it over and access in html file
    context = {}
    #store the quote values given by user from table
    quotes = []
    #list with all states for states dropdown box
    states=['NE', 'WY', 'OH', 'OK', 'AR', 'OR', 'MD', 'MT', 'CT', 'UT', 'GA', 'IN', 'FL', 'TN', 'DC', 'MS', 'CO', 'RI', 'NV', 'KY', 'WA', 'NH', 'MO', 'PA', 'DE', 'ME', 'AL', 'KS', 'SD', 'WI', 'ND', 'NY', 'NM', 'ID', 'IA', 'WV']
    
    #POST request method logic
    if request.method=='POST':

        #For a POST request get all the html textbox,radio button,dropdown box values provided by user in form
        context['customer_id']=request.POST.get('customer_id')
        context['state']=request.POST.get('state')
        context['shop_id']=request.POST.get('shop_id')
        context['location'] = request.POST.get('location')
        context['group_size'] = request.POST.get('group_size')
        context['car_age'] = request.POST.get('car_age')
        context['car_value'] = request.POST.get('car_value')
        context['young_age'] = request.POST.get('young_age')
        context['elder_age'] = request.POST.get('elder_age')
        context['price'] = request.POST.get('price')
        context['married']=request.POST.get('married')
        context['risk'] = request.POST.get('risk')
        context['prev_duration'] = request.POST.get('prev_duration')

        #history values of customer quote details
        table = request.POST.get('table')
        #json data of all the values
        table = json.loads(table)

        #populate quotes list to process it using developed model
        for i, row in enumerate(table):
            quotes.append(row)
        # run concurrent process to predit G
        with concurrent.futures.ThreadPoolExecutor() as executor:
            process = executor.submit(predict_G,context['state'], quotes[-1][-1], quotes[-2][-1])
            G = process.result()
        #predicted quote from the model
        ans = quotes[-1][:6] + [G[0]]
        #print('ans is ',ans)
        ans[len(ans)-1]=int(ans[len(ans)-1])

        #POST request return value
        return render(request, 'Training/display_data.html', {'context': context,'states':states,'ans':ans})

    #GET request return value
    return render(request,'Training/mainpage.html',{'context':context,'states':states})


def Test(request):
    #to navigate to about.html file which has details about ePrediction website
    return render(request,'Training/about.html')

train = TrainingData()

Training/templates/Training/about.html
{% extends 'Training/index.html' %}
{% load static %}
{% block content %}
<!-- Start About area -->
  <div id="about" class="about-area area-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="section-headline text-center">
            <h2>About ePrediction</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <!-- single-well start-->
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="well-left">
            <div class="single-well">
              <a href="#">
								  <img src="{% static 'img/about/1.jpg' %}" alt="">
								</a>
            </div>
          </div>
        </div>
        <!-- single-well end-->
        <div class="col-md-6 col-sm-6 col-xs-12">
          <div class="well-middle">
            <div class="single-well">
              <a href="#">
                <h4 class="sec-head">project Maintenance</h4>
              </a>

              <ul>
                <li>
                  <i class="fa fa-check"></i> Most probable insurance options
                </li>
                <li>
                  <i class="fa fa-check"></i> Most probable insurance option relationships with other options
                </li>
                <li>
                  <i class="fa fa-check"></i> Most probable insurance option relationships with demographics
                </li>
              </ul>
            </div>
          </div>
        </div>
        <!-- End col-->
      </div>
    </div>
  </div>
  <!-- End About area -->

{% endblock %}

Training/templates/Training/display_data.html
{% extends 'Training/index.html' %}
{% load static %}
{% block content %}
<div class="card card-cascade">

  <div class="card-body card-body-cascade text-center">

    <h1 class="card-title" style="color:#3EC1D5"><strong>Customer Details</strong></h1>
    <br>
    <div class="row">
      <div class="col-2 text-center">
      </div>
      <div class="col-4 text-center">
        <h6 class="font-weight-bold">Customer ID</h6>
        <p class="card-text">{{context.customer_id}}</p>
      </div>
      <div class="col-4 text-center">
        <h6 class="font-weight-bold">State</h6>
        <p class="card-text">{{context.state}}</p>
      </div>
    </div>
      
    <div class="row">
      <div class="col-2 text-center">
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold">Shopping ID</h6>    
        <p class="card-text">{{context.shop_id}}</p>
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold">Location Pin Code</h6>    
        <p class="card-text">{{context.location}}</p>
      </div>
    </div>

    <div class="row">
      <div class="col-2 text-center">
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Group Size</h6>    
        <p class="card-text">{{context.group_size}}</p>
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Car Age</h6>    
        <p class="card-text">{{context.car_age}}</p>
      </div>
    </div>

    <div class="row">
      <div class="col-2 text-center">
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Car Value</h6>    
        <p class="card-text">{{context.car_value}}</p>
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Married..?</h6>    
        <p class="card-text">{{context.married}}</p>
      </div>
    </div>

    <div class="row">
      <div class="col-2 text-center">
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Younger Age</h6>    
        <p class="card-text">{{context.young_age}}</p>
      </div>
      <div class="col-4">
        <h6 class="font-weight-bold indigo-text py-2">Elder Age</h6>    
        <p class="card-text">{{context.elder_age}}</p>
      </div>
    </div>
      

    
    <br>
    <div class="row">
    
      <div class="col-4 text-center">
      </div>
      <div class="col-4 text-center">      
          <h1 class="card-title text-center" style="color:#3EC1D5"><strong>Quote Details</strong></h1>
          <br> 
          
        <table class="table table-hover" style="height:70px;border: 1px solid black;">
          <thead>
            <tr>
              <th scope="col">A</th>
              <th scope="col">B</th>
              <th scope="col">C</th>
              <th scope="col">D</th>
              <th scope="col">E</th>
              <th scope="col">F</th>
              <th scope="col">G</th>
            </tr>
          </thead>
          <tbody >
            <tr>
              <td scope="row">{{ans.0}}</td>
              <td scope="row">{{ans.1}}</td>
              <td scope="row">{{ans.2}}</td>
              <td scope="row">{{ans.3}}</td>
              <td scope="row">{{ans.4}}</td>
              <td scope="row">{{ans.5}}</td>
              <td scope="row">{{ans.6}}</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-4">
      </div>
    </div>



  </div>
  <div class="row">
  <div class="col-4">
      </div>
      <div class="col-4 text-center">
      <a class="ready-btn right-btn page-scroll" style="color:black" href="{% url 'training:analysis' %}">Check Analysis</a>
      </div>
  
  </div>
  <br>

</div>
{% endblock %}

Training/templates/Training/index.html
{% load static %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css"
    integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js"
    integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4"
    crossorigin="anonymous"></script>
  <title>All State Insurance</title>
  <meta charset="utf-8">
  <title>eBusiness Bootstrap Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900"
    rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Libraries CSS Files -->
  <link href="{% static 'lib/nivo-slider/css/nivo-slider.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/owl.carousel.css' %}" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/owl.transitions.css' %}" rel="stylesheet">
  <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'lib/venobox/venobox.css' %}" rel="stylesheet">

  <!-- Nivo Slider Theme -->
  <link href="{% static 'css/nivo-slider-theme.css' %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- Responsive Stylesheet File -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

</head>

<body data-spy="scroll" data-target="#navbar-example">

  <div id="preloader"></div>

  <header>
    <!-- header-area start -->
    <div id="sticker" class="header-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12">

            <!-- Navigation -->
            <nav class="navbar navbar-default">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                  data-target=".bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <!-- Brand -->
                <a class="navbar-brand page-scroll sticky-logo nav-left">
                  <h1><span>e</span>Prediction</h1>
                </a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->

              <!-- navbar-collapse -->
            </nav>
            <!-- END: Navigation -->
          </div>
        </div>
      </div>
    </div>
    <!-- header-area end -->
  </header>
  <!-- header end -->

  <!-- Start Slider Area -->
  <div id="home" class="slider-area">
    <div class="bend niceties preview-2">
      <div id="ensign-nivoslider" class="slides">
        <img loading="lazy" alt="…" src="{% static 'img/slider/slider3.jpg' %}" alt="" title="#slider-direction-1" />
        <img loading="lazy" alt="…" src="{% static 'img/slider/slider1.jpg' %}" alt="" title="#slider-direction-2" />
      </div>

      <!-- direction 1 -->
      <div id="slider-direction-1" class="slider-direction slider-one">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-sm-12 col-xs-12">
              <div class="slider-content">
                <!-- layer 1 -->
                <div class="layer-1-1 hidden-xs wow slideInDown" data-wow-duration="2s" data-wow-delay=".2s">
                  <h2 class="title1">Insurance Prediction</h2>
                </div>
                <!-- layer 2 -->
                <div class="layer-1-2 wow slideInUp" data-wow-duration="2s" data-wow-delay=".1s">
                  <h1 class="title2">We're here to help you</h1>
                </div>
                <!-- layer 3 -->
                <div class="layer-1-3 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                  <a class="ready-btn right-btn page-scroll" href="{% url 'training:test' %}">Learn More</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- direction 2 -->
      <div id="slider-direction-2" class="slider-direction slider-two">
        <div class="container">
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="slider-content text-center">
                <div class="layer-1-2 wow slideInUp" data-wow-duration="2s" data-wow-delay=".1s">
                  <h1 class="title2">Get your quote today</h1>
                </div>
                <!-- layer 3 -->
                <div class="layer-1-3 hidden-xs wow slideInUp" data-wow-duration="2s" data-wow-delay=".2s">
                  <a class="ready-btn right-btn page-scroll" href="{% url 'training:main_page' %}">Get Quote</a>
                  <a class="ready-btn right-btn page-scroll" href="{% url 'training:analysis' %}">Check Analysis</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- direction 3 -->

    </div>
  </div>
  <!-- End Slider Area -->


  {% block content%}
  {% endblock%}



  <div class="row">
  </div>
  <!-- Start Testimonials -->
  <div class="testimonials-area">
    <div class="testi-inner area-padding">
      <div class="testi-overly"></div>
      <div class="container ">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <!-- Start testimonials Start -->
            <h1 class="text-center" style="color:white">All State Insurance</h1>
            <div class="testimonial-content text-center">
              <!-- start testimonial carousel -->
              <div class="testimonial-carousel">

              </div>
            </div>
            <!-- End testimonials end -->
          </div>
          <!-- End Right Feature -->
        </div>
      </div>
    </div>
  </div>
  <!-- End Testimonials -->


  <!-- Start contact Area -->
  <div id="contact" class="contact-area">
    <div class="contact-inner area-padding">
      <div class="contact-overly"></div>
      <div class="container ">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="section-headline text-center">
              <h2>Contact us</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <!-- Start contact icon column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="fa fa-mobile"></i>
                <p>
                  Call: 9876543210<br>
                  <span>Monday-Friday (9am-5pm)</span>
                </p>
              </div>
            </div>
          </div>
          <!-- Start contact icon column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="fa fa-envelope-o"></i>
                <p>
                  Email: info@example.com<br>
                  <span>Web: www.example.com</span>
                </p>
              </div>
            </div>
          </div>
          <!-- Start contact icon column -->
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="contact-icon text-center">
              <div class="single-icon">
                <i class="fa fa-map-marker"></i>
                <p>
                  Location: XYZ Street<br>
                  <span>NY 12345, USA</span>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">




          <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

          <!-- JavaScript Libraries -->
          <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
          <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
          <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
          <script src="{% static 'lib/venobox/venobox.min.js' %}"></script>
          <script src="{% static 'lib/knob/jquery.knob.js' %}"></script>
          <script src="{% static 'lib/wow/wow.min.js' %}"></script>
          <script src="{% static 'lib/parallax/parallax.js' %}"></script>
          <script src="{% static 'lib/easing/easing.min.js' %}"></script>
          <script src="{% static 'lib/nivo-slider/js/jquery.nivo.slider.js' %}" type="text/javascript"></script>
          <script src="{% static '/appear/jquery.appear.js' %}"></script>
          <script src="{% static 'lib/isotope/isotope.pkgd.min.js' %}"></script>


          <script src="{% static 'js/main.js' %}"></script>
</body>

</html>